//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poliza()
        {
            this.PolizaPorCliente = new HashSet<PolizaPorCliente>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipoCubrimiento { get; set; }
        public decimal CoberturaPoliza { get; set; }
        public System.DateTime InicioVigencia { get; set; }
        public int PeriodoCobertura { get; set; }
        public System.DateTime FinVigencia { get; set; }
        public decimal PrecioPoliza { get; set; }
        public Nullable<int> IdTipoRiesgo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaPorCliente> PolizaPorCliente { get; set; }
        public virtual TipoCubrimiento TipoCubrimiento { get; set; }
        public virtual TipoRiesgo TipoRiesgo { get; set; }
    }
}
